[package]
name = "bootloader"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "1.0.0"
stm32f4xx-hal = { version = "0.15", features = ["stm32f411", "rt"] }
sha2 = "0.10"
crc-any = "2.0"
defmt = "0.4"
panic-halt = "0.2"